<?php
declare(strict_types=1);
require __DIR__.'/support/Harness.php';
ob_start();
$environment=new TestEnvironment();$db=$environment->db;$suite=new Suite();
$admin=new App\Models\AdminModel($db);$bookings=new App\Models\Booking($db);$seats=new App\Models\SeatSelection($db);$payments=new App\Models\ManualPayment($db);$flights=new App\Models\FlightSearch($db);$tickets=new App\Models\ETicket($db);$users=new App\Models\User($db);
$airline=['name'=>'Test Air','iata_code'=>'TA','icao_code'=>'TST','status'=>'active'];
$airport=['name'=>'Test Airport','iata_code'=>'TST','icao_code'=>'TEST','city'=>'Test City','country'=>'Pakistan','timezone'=>'Asia/Karachi','status'=>'active'];
$flight=['airline_id'=>1,'flight_number'=>'TA123','departure_airport_id'=>1,'arrival_airport_id'=>2,'departure_at'=>(new DateTimeImmutable('+8 days'))->format('Y-m-d\TH:i'),'arrival_at'=>(new DateTimeImmutable('+8 days +2 hours'))->format('Y-m-d\TH:i'),'base_fare'=>'100.25','currency'=>'PKR','status'=>'scheduled'];
$suite->add('unit/security: CSRF is stable, constant-length, rejects missing/array/invalid tokens, and rotates',function(){
    $token=App\Core\Csrf::token();equal(strlen($token),64);equal(App\Core\Csrf::token(),$token);
    foreach([null,[],0,'',str_repeat('0',64)] as $invalid)equal(App\Core\Csrf::verify($invalid),false);
    equal(App\Core\Csrf::verify($token),true);App\Core\Csrf::rotate();equal(App\Core\Csrf::verify($token),false);
});
$suite->add('unit: flash messages are consumed exactly once',function(){App\Core\Session::flash('message','hello');equal(App\Core\Session::pullFlash('message'),'hello');equal(App\Core\Session::pullFlash('message','default'),'default');});
$suite->add('unit/security: login and logout rotate session IDs and tokens, remove old session data',function(){
    $old=session_id();$token=App\Core\Csrf::token();$_SESSION['selected_flight_id']=1;App\Core\Auth::login(['id'=>1,'full_name'=>'One','role'=>'customer']);
    expect(session_id()!==$old);equal(App\Core\Auth::check(),true);expect(!isset($_SESSION['selected_flight_id']));equal(App\Core\Csrf::verify($token),false);
    App\Core\Auth::logout();equal(App\Core\Auth::check(),false);equal(App\Core\Auth::role(),null);
});
$suite->add('integration/security: authentication normalizes email, rejects bad credentials and suspended accounts',function()use($users){
    $auth=new App\Core\AuthService($users);equal($auth->authenticate(' ONE@example.test ','Password123!'),true);equal(App\Core\Auth::role(),'customer');
    App\Core\Auth::logout();foreach([['one@example.test','wrong'],['suspended@example.test','Password123!'],["' OR 1=1 --",'Password123!']] as [$email,$password])equal($auth->authenticate($email,$password),false);
});
$suite->add('integration: authentication upgrades an old password hash',function()use($db,$users){
    $db->prepare('UPDATE users SET password_hash=? WHERE id=1')->execute([password_hash('Password123!',PASSWORD_BCRYPT,['cost'=>4])]);
    equal((new App\Core\AuthService($users))->authenticate('one@example.test','Password123!'),true);
    equal(password_needs_rehash($users->findByEmail('one@example.test')['password_hash'],PASSWORD_DEFAULT),false);
});
$suite->add('integration: customer creation, profile privacy and duplicate email constraint',function()use($users){
    $created=$users->createCustomer('<script>alert(1)</script>','new@example.test',password_hash('Password123!',PASSWORD_DEFAULT));equal($created['role'],'customer');
    $profile=$users->profileForCustomer($created['id']);expect(!isset($profile['password_hash']));equal($users->profileForCustomer(3),null);
    rejects(fn()=> $users->createCustomer('Again','new@example.test','hash'),PDOException::class);
});
$suite->add('integration: admin airline create, update, unchanged update and missing-record handling',function()use($admin,$airline,$environment){
    $admin->save('airlines',$airline);$id=(int)$environment->db->lastInsertId();$admin->save('airlines',$airline+['id'=>$id]);
    $admin->save('airlines',array_replace($airline,['id'=>$id,'name'=>'Updated']));equal($environment->scalar('SELECT name FROM airlines WHERE id=?',[$id]),'Updated');
    rejects(fn()=> $admin->save('airlines',$airline+['id'=>999999]));
});
foreach([['iata_code'=>'!'],['icao_code'=>'TOOLONG'],['name'=>''],['status'=>'deleted'],['id'=>'1 OR 1=1']] as $index=>$invalid)$suite->add('unit: reject invalid airline fields '.$index,fn()=>rejects(fn()=> $admin->save('airlines',array_replace($airline,$invalid))));
$suite->add('integration: admin airport create and edit',function()use($admin,$airport,$environment){$admin->save('airports',$airport);$id=(int)$environment->db->lastInsertId();$admin->save('airports',array_replace($airport,['id'=>$id,'city'=>'Updated City']));equal($environment->scalar('SELECT city FROM airports WHERE id=?',[$id]),'Updated City');});
foreach([['iata_code'=>'XX'],['icao_code'=>'X'],['country'=>''],['timezone'=>'No/Such_Zone'],['status'=>[]]] as $index=>$invalid)$suite->add('unit: reject invalid airport fields '.$index,fn()=>rejects(fn()=> $admin->save('airports',array_replace($airport,$invalid))));
$suite->add('integration: admin flight create and unchanged update',function()use($admin,$flight,$environment){$admin->save('flights',$flight);$id=(int)$environment->db->lastInsertId();$admin->save('flights',$flight+['id'=>$id]);equal($environment->scalar('SELECT flight_number FROM flights WHERE id=?',[$id]),'TA123');});
foreach([['arrival_airport_id'=>1],['departure_at'=>'2026-02-30T12:00'],['arrival_at'=>'2020-01-01T10:00'],['base_fare'=>'0'],['base_fare'=>'1.234'],['currency'=>'P'],['flight_number'=>"';DROP"],['airline_id'=>[]]] as $index=>$invalid)$suite->add('unit: reject invalid flight fields '.$index,fn()=>rejects(fn()=> $admin->save('flights',array_replace($flight,$invalid))));
$suite->add('integration: seat generation is idempotent, normalizes duplicate letters and preserves reserved seats',function()use($admin,$environment){$booking=$environment->booking();$environment->assign($booking);$before=$environment->scalar('SELECT COUNT(*) FROM booking_seats');equal($admin->generateSeats(1,2,['a','A','b'],'economy'),0);equal($environment->scalar('SELECT COUNT(*) FROM booking_seats'),$before);});
$suite->add('regression: all eleven letters offered by the seat-generation form are accepted',fn()=>equal($admin->generateSeats(1,1,range('A','K'),'business'),7));
foreach([[0,1,['A'],'economy'],[1,101,['A'],'economy'],[1,1,[],'economy'],[1,1,['<'],'economy'],[1,1,['A'],'invalid'],[999,1,['A'],'economy']] as $index=>$args)$suite->add('unit: reject invalid seat generation '.$index,fn()=>rejects(fn()=> $admin->generateSeats(...$args)));
$suite->add('integration: bulk seat status cannot change reserved seats',function()use($admin,$environment){$booking=$environment->booking();$environment->assign($booking);$admin->seatStatus(1,'blocked');equal($environment->scalar('SELECT status FROM seats WHERE id=1'),'available');equal($environment->scalar('SELECT status FROM seats WHERE id=2'),'blocked');});
$suite->add('regression: admin availability excludes reserved seats and reports zero for flights without seats',function()use($admin,$environment){$booking=$environment->booking();$environment->assign($booking);$rows=array_column($admin->all('seats'),null,'flight_id');equal((int)$rows[1]['available'],5);equal((int)$rows[3]['available'],0);});
$suite->add('integration: flight search excludes inactive, departed, blocked and reserved stock',function()use($flights,$environment,$db){equal($flights->seatAvailability([1])[0]['available_seats'],6);$b=$environment->booking();$environment->assign($b);equal($flights->findAvailable(1)['available_seats'],5);equal($flights->findAvailable(3),null);$db->exec("UPDATE airlines SET status='inactive' WHERE id=1");equal($flights->allAvailable(),[]);});
$suite->add('integration: flight search filters route and date, sold-out counts reach zero',function()use($flights,$environment,$db){$date=substr($environment->scalar('SELECT departure_at FROM flights WHERE id=1'),0,10);equal(count($flights->search(1,2,$date)),2);equal($flights->search(2,1,$date),[]);$db->exec("UPDATE seats SET status='blocked' WHERE flight_id=1");equal($flights->seatAvailability([1])[0]['available_seats'],0);equal($flights->findAvailable(1),null);});
$suite->add('integration: booking creates unique PNRs, decimal totals and passengers atomically',function()use($environment,$bookings){$a=$environment->booking(1,2);$b=$environment->booking(1,1);equal($a['total_amount'],'20.50');expect($a['pnr']!==$b['pnr']);equal(count($bookings->findForCustomer($a['id'],1)['passengers']),2);});
foreach([['9.99','PKR'],['10.25','USD']] as $index=>[$fare,$currency])$suite->add('regression: stale booking fare/currency is rejected '.$index,function()use($bookings,$environment,$fare,$currency){rejects(fn()=> $bookings->createPending(1,1,[$environment->passenger()],$fare,$currency));equal((int)$environment->scalar('SELECT COUNT(*) FROM bookings'),0);});
$suite->add('integration: insufficient seats and invalid passenger insertion roll back the whole booking',function()use($bookings,$environment){rejects(fn()=> $environment->booking(1,7),App\Core\InsufficientSeats::class);$passenger=$environment->passenger();$passenger['gender']='invalid';rejects(fn()=> $bookings->createPending(1,1,[$passenger],'10.25','PKR'),PDOException::class);equal((int)$environment->scalar('SELECT COUNT(*) FROM bookings'),0);});
foreach(['cancelled','departed','completed'] as $status)$suite->add('integration: reject booking on '.$status.' flight',function()use($db,$environment,$status){$db->prepare('UPDATE flights SET status=? WHERE id=1')->execute([$status]);rejects(fn()=> $environment->booking());});
$suite->add('security: all customer reads exclude another customer booking, payment and ticket data',function()use($environment,$bookings,$seats,$payments,$tickets){$b=$environment->booking();equal($bookings->findForCustomer($b['id'],2),null);equal($bookings->listForCustomer(2),[]);equal($seats->booking($b['id'],2),null);equal($seats->pendingBookings(2),[]);equal($payments->booking($b['id'],2),null);equal($payments->history($b['id'],2),[]);equal($payments->bookingsForCustomer(2),[]);equal($tickets->forCustomer(2),[]);});
$suite->add('integration/security: duplicate, foreign-flight and foreign-passenger seat selections roll back',function()use($environment,$seats){$b=$environment->booking(1,2);$selection=$environment->assign($b,1,[1,2]);$ids=array_keys($selection);foreach([[$ids[0]=>1,$ids[1]=>1],[$ids[0]=>1,$ids[1]=>9],[$ids[0]=>1,999=>2],[$ids[0]=>1]] as $invalid)rejects(fn()=> $seats->save($b['id'],1,$invalid));equal((int)$environment->scalar('SELECT COUNT(*) FROM booking_seats'),2);});
$suite->add('integration: competing reservation cannot steal a seat or remove prior assignments',function()use($environment,$seats){$a=$environment->booking();$b=$environment->booking(2);$environment->assign($a,1,[1]);$old=$environment->assign($b,2,[2]);$id=array_key_first($old);rejects(fn()=> $seats->save($b['id'],2,[$id=>1]),App\Core\SeatUnavailable::class);equal((int)$environment->scalar('SELECT seat_id FROM booking_seats WHERE booking_id=?',[$b['id']]),2);});
$suite->add('security: another customer cannot save seats, cancel or submit payment',function()use($environment,$seats,$bookings,$payments){$b=$environment->booking();$selection=$environment->assign($b);rejects(fn()=> $seats->save($b['id'],2,$selection));rejects(fn()=> $bookings->cancelForCustomer($b['id'],2));rejects(fn()=> $payments->submit($b['id'],2,$environment->payment($b)));equal($environment->scalar('SELECT status FROM bookings WHERE id=?',[$b['id']]),'pending');});
$suite->add('integration: payment requires every passenger seat before submission',function()use($environment){$b=$environment->booking();rejects(fn()=> $environment->submitted($b));equal((int)$environment->scalar('SELECT COUNT(*) FROM payments'),0);});
foreach([['method'=>'card'],['sender_name'=>''],['transaction_reference'=>''],['amount'=>'0'],['amount'=>'1e3'],['amount'=>'1.234'],['paid_at'=>'2026-02-30T10:00'],['paid_at'=>'2099-01-01T12:00'],['remarks'=>str_repeat('a',2001)]] as $index=>$invalid)$suite->add('unit/integration: reject invalid payment input '.$index,function()use($environment,$payments,$invalid){$b=$environment->booking();$environment->assign($b);rejects(fn()=> $payments->submit($b['id'],1,array_replace($environment->payment($b),$invalid)));equal((int)$environment->scalar('SELECT COUNT(*) FROM payments'),0);});
$suite->add('integration: payment timestamp before booking is rejected',function()use($environment,$payments){$b=$environment->booking();$environment->assign($b);rejects(fn()=> $payments->submit($b['id'],1,array_replace($environment->payment($b),['paid_at'=>(new DateTimeImmutable('-1 day'))->format('Y-m-d\TH:i')])));});
$suite->add('integration: duplicate active submissions rejected; rejected payment permits a new reference',function()use($environment,$admin,$payments){$b=$environment->booking();$environment->assign($b);$id=$environment->submitted($b);rejects(fn()=> $environment->submitted($b));$admin->reviewPayment($id,'rejected');$payments->submit($b['id'],1,$environment->payment($b,'REF-002'));equal(count($payments->history($b['id'],1)),2);});
$suite->add('functional/integration: reserve, pay, verify and issue exactly one ticket per passenger',function()use($environment,$admin,$tickets,$seats){$b=$environment->booking(1,2);$environment->assign($b,1,[1,2]);$id=$environment->submitted($b);$admin->reviewPayment($id,'verified');equal($environment->scalar('SELECT status FROM bookings WHERE id=?',[$b['id']]),'confirmed');equal(count($tickets->forCustomer(1)),2);equal($seats->booking($b['id'],1),null);rejects(fn()=> $admin->reviewPayment($id,'verified'));equal(count($tickets->forCustomer(1)),2);});
$suite->add('regression: verification of incorrect amount rolls back payment and creates no tickets',function()use($environment,$admin,$db){$b=$environment->booking();$environment->assign($b);$id=$environment->submitted($b);$db->exec('UPDATE payments SET amount=1 WHERE id='.$id);rejects(fn()=> $admin->reviewPayment($id,'verified'));equal($environment->scalar('SELECT status FROM payments WHERE id=?',[$id]),'pending');equal((int)$environment->scalar('SELECT COUNT(*) FROM e_tickets'),0);});
$suite->add('regression: verification cannot ticket a cancelled flight',function()use($environment,$admin,$db){$b=$environment->booking();$environment->assign($b);$id=$environment->submitted($b);$db->exec("UPDATE flights SET status='cancelled' WHERE id=1");rejects(fn()=> $admin->reviewPayment($id,'verified'));equal($environment->scalar('SELECT status FROM payments WHERE id=?',[$id]),'pending');});
$suite->add('regression: verification rejects a blocked assigned seat and rolls back',function()use($environment,$admin,$db){$b=$environment->booking();$environment->assign($b);$id=$environment->submitted($b);$db->exec("UPDATE seats SET status='blocked' WHERE id=1");rejects(fn()=> $admin->reviewPayment($id,'verified'));equal($environment->scalar('SELECT status FROM payments WHERE id=?',[$id]),'pending');});
$suite->add('integration: admin cannot confirm without payment or complete a future booking',function()use($environment,$admin){$b=$environment->booking();rejects(fn()=> $admin->bookingStatus($b['id'],'confirmed'));$environment->assign($b);$id=$environment->submitted($b);$admin->reviewPayment($id,'verified');rejects(fn()=> $admin->bookingStatus($b['id'],'completed'));});
foreach(['customer','admin'] as $actor)$suite->add('functional: '.$actor.' cancellation releases seats, voids tickets and cannot repeat',function()use($environment,$admin,$bookings,$actor){$b=$environment->booking();$environment->assign($b);$id=$environment->submitted($b);$admin->reviewPayment($id,'verified');if($actor==='customer')$bookings->cancelForCustomer($b['id'],1);else $admin->bookingStatus($b['id'],'cancelled');equal((int)$environment->scalar('SELECT COUNT(*) FROM booking_seats'),0);equal($environment->scalar('SELECT status FROM e_tickets'),'void');equal($environment->scalar('SELECT status FROM seats WHERE id=1'),'available');rejects(fn()=> $bookings->cancelForCustomer($b['id'],1));});
$suite->add('regression: dashboard PKR revenue excludes verified payments in other currencies',function()use($environment,$admin){$b=$environment->booking();$environment->assign($b);$admin->reviewPayment($environment->submitted($b),'verified');$usd=$environment->booking(2,1,2);$environment->assign($usd,2,[9]);$admin->reviewPayment($environment->submitted($usd,2),'verified');equal((float)$admin->dashboard()['revenue'],10.25);});
$suite->add('database: foreign keys reject orphan bookings and cross-booking passenger seats',function()use($environment,$db){rejects(fn()=> $db->exec("INSERT INTO bookings(user_id,flight_id,pnr,total_amount) VALUES(999,1,'INVALID',10.25)"),PDOException::class);$a=$environment->booking();$b=$environment->booking(2);$p=(int)$environment->scalar('SELECT id FROM passengers WHERE booking_id=?',[$a['id']]);rejects(fn()=> $db->prepare('INSERT INTO booking_seats(booking_id,seat_id,passenger_id) VALUES(?,?,?)')->execute([$b['id'],1,$p]),PDOException::class);});
$suite->add('database: unique seat and ticket constraints prevent duplicate allocation',function()use($environment,$db,$admin){$a=$environment->booking();$selection=$environment->assign($a);$admin->reviewPayment($environment->submitted($a),'verified');$p=array_key_first($selection);rejects(fn()=> $db->prepare('INSERT INTO booking_seats(booking_id,seat_id,passenger_id) VALUES(?,?,?)')->execute([$a['id'],1,$p]),PDOException::class);rejects(fn()=> $db->prepare('INSERT INTO e_tickets(booking_id,passenger_id,ticket_number) VALUES(?,?,?)')->execute([$a['id'],$p,'DUPLICATE']),PDOException::class);});
$failures=$suite->run(fn()=> $environment->reset());
$environment->cleanup();session_write_close();$output=ob_get_clean();echo $output;exit($failures?1:0);
