<?php
declare(strict_types=1);
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$nav=['dashboard'=>'Overview','flights'=>'Flight schedules','seats'=>'Seats & availability','bookings'=>'Bookings','payments'=>'Review payments','airlines'=>'Airlines','airports'=>'Airports'];
$path=static fn($key)=>$key==='dashboard'?'/admin':'/admin/'.$key;
$post='/admin/action';
require BASE_PATH.'/app/Views/layouts/admin-start.php';
?>
<?php if($success): ?><div class="admin-alert success" role="status" data-admin-feedback><?= $e($success) ?><?php if($section==='flights'): ?><p class="admin-next-step">Next: <a href="/admin/seats#admin-create">create or check seat availability</a> before customers book.</p><?php elseif($section==='airlines'||$section==='airports'): ?><p class="admin-next-step">Ready to continue? <a href="/admin/flights#admin-create">Schedule a flight</a>.</p><?php endif ?></div><?php endif ?><?php if($errors): ?><div class="admin-alert error" role="alert" data-admin-feedback><ul><?php foreach($errors as $error): ?><li><?= $e($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<?php require BASE_PATH.'/app/Views/admin/page-intro.php'; ?>
<?php require BASE_PATH.'/app/Views/admin/workflow-help.php'; ?>
<?php require BASE_PATH.'/app/Views/admin/create-form.php'; ?>
<?php if($section==='dashboard'): ?>
<?php require BASE_PATH.'/app/Views/admin/dashboard.php'; ?>
<?php elseif(in_array($section,['airlines','airports'],true)): ?>

<section class="admin-card"><div class="card-heading"><div><h2><?= ucfirst($section) ?></h2><p><?= count($rows) ?> records</p></div></div><div class="table-wrap" data-admin-table><table><thead><tr><?php if($section==='airlines'): ?><th>Name</th><th>IATA</th><th>ICAO</th><th>Status</th><th>Actions</th><?php else: ?><th>Name / Codes</th><th>City / Country</th><th>Timezone</th><th>Status</th><th>Actions</th><?php endif ?></tr></thead><tbody>
<?php foreach($rows as $r): ?><tr data-row-status="<?= $e($r['status']) ?>"><?php $editFormId='admin-edit-'.$section.'-'.(int)$r['id']; ?><?php if($section==='airlines'): ?><td><input form="<?= $editFormId ?>"  name="name" value="<?= $e($r['name']) ?>" required></td><td><input form="<?= $editFormId ?>"  name="iata_code" value="<?= $e($r['iata_code']) ?>" maxlength="2" required></td><td><input form="<?= $editFormId ?>"  name="icao_code" value="<?= $e($r['icao_code']) ?>"></td><?php else: ?><td><input form="<?= $editFormId ?>"  name="name" value="<?= $e($r['name']) ?>" required><input form="<?= $editFormId ?>"  name="iata_code" value="<?= $e($r['iata_code']) ?>" maxlength="3" required><input form="<?= $editFormId ?>"  name="icao_code" value="<?= $e($r['icao_code']) ?>"></td><td><input form="<?= $editFormId ?>"  name="city" value="<?= $e($r['city']) ?>" required><input form="<?= $editFormId ?>"  name="country" value="<?= $e($r['country']) ?>" required></td><td><input form="<?= $editFormId ?>"  name="timezone" value="<?= $e($r['timezone']) ?>" required></td><?php endif ?><td><select form="<?= $editFormId ?>"  name="status"><option <?= $r['status']==='active'?'selected':'' ?>>active</option><option <?= $r['status']==='inactive'?'selected':'' ?>>inactive</option></select></td><td><form id="<?= $editFormId ?>" class="admin-record-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="<?= $section ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="<?= $path($section) ?>">
<button class="small-button" type="submit">Save changes</button><span class="admin-unsaved" aria-live="polite"></span></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No <?= $e($section) ?> yet. Use the form above to add your first record.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='flights'): ?>

<section class="admin-card"><div class="card-heading"><div><h2>Flight schedule</h2><p><?= count($rows) ?> flights · Change fare, schedule, and status.</p></div></div><div class="table-wrap" data-admin-table><table><thead><tr><th>Flight / route</th><th>Schedule</th><th>Fare / capacity</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr data-row-status="<?= $e($r['status']) ?>"><?php $editFormId='admin-edit-'.$section.'-'.(int)$r['id']; ?><td><strong><?= $e($r['flight_number']) ?></strong><small><?= $e($r['airline'].' · '.$r['departure'].' → '.$r['arrival']) ?></small><a class="admin-row-link" href="/admin/seats?q=<?= rawurlencode($r['flight_number']) ?><?= (int)$r['capacity']===0?'#admin-create':'' ?>"><?= (int)$r['capacity']===0?'Create seats':'Manage seats' ?> &rarr;</a></td><td><input form="<?= $editFormId ?>"  type="datetime-local" name="departure_at" value="<?= $e(date('Y-m-d\TH:i',strtotime($r['departure_at']))) ?>" required><input form="<?= $editFormId ?>"  type="datetime-local" name="arrival_at" value="<?= $e(date('Y-m-d\TH:i',strtotime($r['arrival_at']))) ?>" required></td><td><input form="<?= $editFormId ?>"  type="number" name="base_fare" min="0.01" step="0.01" value="<?= $e($r['base_fare']) ?>" required><small><?= (int)$r['reserved'] ?> booked / <?= (int)$r['capacity'] ?> seats · <?= $e($r['currency']) ?></small></td><td><select form="<?= $editFormId ?>"  name="status"><?php foreach(['scheduled','boarding','departed','completed','cancelled'] as $s): ?><option <?= $r['status']===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select></td><td><form id="<?= $editFormId ?>" class="admin-record-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="flights"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/flights"><input type="hidden" name="airline_id" value="<?= (int)$r['airline_id'] ?>"><input type="hidden" name="departure_airport_id" value="<?= (int)$r['departure_airport_id'] ?>"><input type="hidden" name="arrival_airport_id" value="<?= (int)$r['arrival_airport_id'] ?>"><input type="hidden" name="flight_number" value="<?= $e($r['flight_number']) ?>"><input type="hidden" name="currency" value="<?= $e($r['currency']) ?>"><button class="small-button" type="submit">Save changes</button><span class="admin-unsaved" aria-live="polite"></span></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No flights scheduled. Add an airline and two airports, then schedule your first flight above.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='seats'): ?>

<section class="admin-card"><div class="card-heading"><div><h2>Seat availability</h2><p>Choose a flight below to update all seats without a reservation. Reserved seats stay unchanged.</p></div></div><div class="table-wrap" data-admin-table><table><thead><tr><th>Flight</th><th>Route / departure</th><th>Capacity</th><th>Availability</th><th>Update unreserved seats</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr data-row-status="<?= $e($r['status'] ?? '') ?>"><td><strong><?= $e($r['flight_number']) ?></strong></td><td><?= $e($r['departure'].' → '.$r['arrival']) ?><small><?= $e($r['departure_at']) ?></small></td><td><?= (int)$r['capacity'] ?></td><td><?= (int)$r['available'] ?> available · <?= (int)$r['blocked'] ?> blocked</td><td><form class="inline-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="seat_status"><input type="hidden" name="flight_id" value="<?= (int)$r['flight_id'] ?>"><input type="hidden" name="return_to" value="/admin/seats"><select name="status"><option>available</option><option>blocked</option><option>unavailable</option></select><button class="small-button">Update seat availability</button></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No flights available. Schedule a flight first, then return here to create its seats.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='bookings'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Find and manage bookings</h2><p>Reservation details and status.</p></div></div><div class="table-wrap" data-admin-table><table><thead><tr><th>Booking reference / customer</th><th>Flight</th><th>Passengers</th><th>Amount</th><th>Status / update</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr data-row-status="<?= $e($r['status'] ?? '') ?>"><td><strong><?= $e($r['pnr']) ?></strong><small><?= $e($r['full_name'].' · '.$r['email']) ?></small><a class="admin-row-link" href="/admin/<?= $section==='bookings'?'payments':'bookings' ?>?q=<?= rawurlencode($r['pnr']) ?>"><?= $section==='bookings'?'Find payment':'Find booking' ?> &rarr;</a></td><td><?= $e($r['flight_number'].' · '.$r['departure'].' → '.$r['arrival']) ?></td><td><details class="admin-passenger-details"><summary>View passengers</summary><p><?= $e($r['passengers']??'No passenger details available.') ?></p></details></td><td><?= $e($r['currency'].' '.$r['total_amount']) ?></td><td><form class="inline-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="booking_status"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/bookings"><select name="status"><?php foreach(['pending','confirmed','cancelled','completed','expired'] as $s): ?><option <?= $r['status']===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select><button class="small-button" type="submit">Save changes</button><span class="admin-unsaved" aria-live="polite"></span></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No bookings yet.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='payments'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Payment review</h2><p>Review the submitted payment details, then verify or reject.</p></div></div><div class="table-wrap" data-admin-table><table><thead><tr><th>Booking / customer</th><th>Amount / method</th><th>Sender / reference</th><th>Payment time / remarks</th><th>Status / review</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr data-row-status="<?= $e($r['status'] ?? '') ?>"><td><strong><?= $e($r['pnr']) ?></strong><small><?= $e($r['full_name'].' · '.$r['email']) ?></small><a class="admin-row-link" href="/admin/<?= $section==='bookings'?'payments':'bookings' ?>?q=<?= rawurlencode($r['pnr']) ?>"><?= $section==='bookings'?'Find payment':'Find booking' ?> &rarr;</a></td><td><?= $e($r['currency'].' '.$r['amount']) ?><small><?= $e(str_replace('_',' ',$r['method'])) ?></small></td><td><?= $e($r['sender_name']??'—') ?><small><?= $e($r['transaction_reference']??'—') ?></small><?php if($r['proof_path']): ?><a class="proof-link" href="/admin/payment-proof?id=<?= (int)$r['id'] ?>">Download proof</a><?php else: ?><small>No proof attached</small><?php endif ?></td><td><?= $e($r['paid_at']??'—') ?><?php if($r['remarks']): ?><small><?= $e($r['remarks']) ?></small><?php endif ?></td><td><span class="badge <?= $e($r['status']) ?>"><?= $e($r['status']) ?></span><?php if(in_array($r['status'],['pending','submitted'],true)): ?><form class="review-actions" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="payment"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/payments"><button class="small-button verify" name="decision" value="verified">Verify payment</button><button class="small-button reject" name="decision" value="rejected">Reject payment</button></form><?php else: ?><small>Booking <?= $e($r['booking_status']) ?></small><?php endif ?></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No payments submitted.</td></tr><?php endif ?></tbody></table></div></section>
<?php endif ?>
<?php require BASE_PATH.'/app/Views/layouts/admin-end.php'; ?>
<script defer src="/assets/js/admin-workspace.js"></script>
<script defer src="/assets/js/admin-usability.js"></script>
<?php require BASE_PATH.'/app/Views/layouts/footer.php'; ?>
