<?php
declare(strict_types=1);
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$nav=['dashboard'=>'Dashboard','airlines'=>'Airlines','airports'=>'Airports','flights'=>'Flights','seats'=>'Seats','bookings'=>'Bookings','payments'=>'Payments'];
$path=static fn($key)=>$key==='dashboard'?'/admin':'/admin/'.$key;
$post='/admin/action';
require BASE_PATH.'/app/Views/layouts/header.php';
?>
<link rel="stylesheet" href="/assets/css/admin.css">
<div class="admin-shell admin-section-<?= $e($section) ?>">
<button class="admin-menu-toggle" type="button" aria-expanded="false" aria-controls="admin-sidebar" onclick="document.body.classList.toggle('admin-nav-open');this.setAttribute('aria-expanded',document.body.classList.contains('admin-nav-open'))">☰ <span>Menu</span></button>
<aside class="admin-sidebar" id="admin-sidebar"><a class="admin-brand" href="/admin">AeroBook <small>ADMIN</small></a><nav aria-label="Admin sections">
<?php foreach($nav as $key=>$label): ?><a class="<?= $section===$key?'active':'' ?>" href="<?= $path($key) ?>"><?= $e($label) ?><?php if($key==='payments'&&!empty($stats['pending_payments'])): ?><b><?= (int)$stats['pending_payments'] ?></b><?php endif ?></a><?php endforeach ?>
</nav><div class="admin-user"><span><?= $e($adminName) ?></span><form method="post" action="/admin/logout"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><button type="submit">Sign out</button></form></div></aside>
<main class="admin-main"><header class="admin-top"><div><p class="admin-eyebrow">AeroBook operations</p><h1><?= $section==='dashboard'?'Dashboard':$e($title) ?></h1></div><span class="admin-date"><?= date('D, M j, Y') ?></span></header>
<?php if($success): ?><div class="admin-alert success"><?= $e($success) ?></div><?php endif ?><?php if($errors): ?><div class="admin-alert error"><ul><?php foreach($errors as $error): ?><li><?= $e($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<?php if($section==='dashboard'): ?>
<section class="stat-grid"><?php foreach(['bookings'=>'Bookings','flights'=>'Flights','payments'=>'Payments','users'=>'Users'] as $key=>$label): ?><article class="stat-card"><span><?= $label ?></span><strong><?= number_format((int)$stats[$key]) ?></strong><?php if($key==='payments'): ?><small><?= number_format((int)$stats['pending_payments']) ?> awaiting review</small><?php endif ?></article><?php endforeach ?></section>
<article class="admin-card revenue-card"><div><span>Verified payment volume</span><strong><?= $e(number_format((float)$stats['revenue'],2)) ?> PKR</strong></div><a class="admin-button" href="/admin/payments">Review payments</a></article>
<section class="admin-card"><div class="card-heading"><div><h2>Recent bookings</h2><p>Latest passenger reservations</p></div><a href="/admin/bookings">All bookings →</a></div><div class="table-wrap"><table><thead><tr><th>PNR</th><th>Customer</th><th>Flight</th><th>Booked</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($stats['recent_bookings'] as $r): ?><tr><td><strong><?= $e($r['pnr']) ?></strong></td><td><?= $e($r['full_name']) ?></td><td><?= $e($r['flight_number']) ?></td><td><?= $e($r['booked_at']) ?></td><td><?= $e($r['currency'].' '.$r['total_amount']) ?></td><td><span class="badge <?= $e($r['status']) ?>"><?= $e($r['status']) ?></span></td></tr><?php endforeach ?><?php if(!$stats['recent_bookings']): ?><tr><td colspan="6" class="empty">No bookings yet.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif(in_array($section,['airlines','airports'],true)): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Add <?= $section==='airlines'?'airline':'airport' ?></h2><p>Existing records can be updated in the table.</p></div></div><form class="admin-form wide-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="<?= $section ?>"><input type="hidden" name="return_to" value="<?= $path($section) ?>">
<label>Name<input name="name" maxlength="180" required></label><label>IATA<input name="iata_code" maxlength="<?= $section==='airlines'?2:3 ?>" required></label><label>ICAO<input name="icao_code" maxlength="<?= $section==='airlines'?3:4 ?>"></label>
<?php if($section==='airports'): ?><label>City<input name="city" maxlength="120" required></label><label>Country<input name="country" maxlength="120" required></label><label>Timezone<input name="timezone" maxlength="64" placeholder="Asia/Karachi" required></label><?php endif ?><label>Status<select name="status"><option>active</option><option>inactive</option></select></label><button class="admin-button">Add <?= $section==='airlines'?'airline':'airport' ?></button></form></section>
<section class="admin-card"><div class="card-heading"><div><h2><?= ucfirst($section) ?></h2><p><?= count($rows) ?> records</p></div></div><div class="table-wrap"><table><thead><tr><?php if($section==='airlines'): ?><th>Name</th><th>IATA</th><th>ICAO</th><th>Status</th><th>Save</th><?php else: ?><th>Name / Codes</th><th>City / Country</th><th>Timezone</th><th>Status</th><th>Save</th><?php endif ?></tr></thead><tbody>
<?php foreach($rows as $r): ?><tr><form method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="<?= $section ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="<?= $path($section) ?>">
<?php if($section==='airlines'): ?><td><input name="name" value="<?= $e($r['name']) ?>" required></td><td><input name="iata_code" value="<?= $e($r['iata_code']) ?>" maxlength="2" required></td><td><input name="icao_code" value="<?= $e($r['icao_code']) ?>"></td><?php else: ?><td><input name="name" value="<?= $e($r['name']) ?>" required><input name="iata_code" value="<?= $e($r['iata_code']) ?>" maxlength="3" required><input name="icao_code" value="<?= $e($r['icao_code']) ?>"></td><td><input name="city" value="<?= $e($r['city']) ?>" required><input name="country" value="<?= $e($r['country']) ?>" required></td><td><input name="timezone" value="<?= $e($r['timezone']) ?>" required></td><?php endif ?><td><select name="status"><option <?= $r['status']==='active'?'selected':'' ?>>active</option><option <?= $r['status']==='inactive'?'selected':'' ?>>inactive</option></select></td><td><button class="small-button">Save</button></td></form></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="6" class="empty">No records yet.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='flights'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Schedule a flight</h2><p>Capacity is determined by generated seats.</p></div></div><form class="admin-form wide-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="flights"><input type="hidden" name="return_to" value="/admin/flights"><label>Airline<select name="airline_id" required><?php foreach($options['airlines'] as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $e($o['name']) ?></option><?php endforeach ?></select></label><label>Flight number<input name="flight_number" maxlength="10" required></label><?php foreach(['departure_airport_id'=>'From','arrival_airport_id'=>'To'] as $key=>$label): ?><label><?= $label ?><select name="<?= $key ?>" required><?php foreach($options['airports'] as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $e($o['iata_code'].' · '.$o['city']) ?></option><?php endforeach ?></select></label><?php endforeach ?><label>Departure<input type="datetime-local" name="departure_at" required></label><label>Arrival<input type="datetime-local" name="arrival_at" required></label><label>Base fare<input name="base_fare" type="number" min="0.01" step="0.01" required></label><label>Currency<input name="currency" value="PKR" maxlength="3" required></label><label>Status<select name="status"><?php foreach(['scheduled','boarding','departed','completed','cancelled'] as $s): ?><option><?= $s ?></option><?php endforeach ?></select></label><button class="admin-button">Create flight</button></form></section>
<section class="admin-card"><div class="card-heading"><div><h2>Flight schedule</h2><p><?= count($rows) ?> flights · Change fare, schedule, and status.</p></div></div><div class="table-wrap"><table><thead><tr><th>Flight / route</th><th>Schedule</th><th>Fare / capacity</th><th>Status</th><th>Save</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><form method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="flights"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/flights"><input type="hidden" name="airline_id" value="<?= (int)$r['airline_id'] ?>"><input type="hidden" name="departure_airport_id" value="<?= (int)$r['departure_airport_id'] ?>"><input type="hidden" name="arrival_airport_id" value="<?= (int)$r['arrival_airport_id'] ?>"><input type="hidden" name="flight_number" value="<?= $e($r['flight_number']) ?>"><input type="hidden" name="currency" value="<?= $e($r['currency']) ?>"><td><strong><?= $e($r['flight_number']) ?></strong><small><?= $e($r['airline'].' · '.$r['departure'].' → '.$r['arrival']) ?></small></td><td><input type="datetime-local" name="departure_at" value="<?= $e(date('Y-m-d\TH:i',strtotime($r['departure_at']))) ?>" required><input type="datetime-local" name="arrival_at" value="<?= $e(date('Y-m-d\TH:i',strtotime($r['arrival_at']))) ?>" required></td><td><input type="number" name="base_fare" min="0.01" step="0.01" value="<?= $e($r['base_fare']) ?>" required><small><?= (int)$r['reserved'] ?> booked / <?= (int)$r['capacity'] ?> seats · <?= $e($r['currency']) ?></small></td><td><select name="status"><?php foreach(['scheduled','boarding','departed','completed','cancelled'] as $s): ?><option <?= $r['status']===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select></td><td><button class="small-button">Save</button></td></form></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No flights scheduled.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='seats'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Generate seat grid</h2><p>Existing seat numbers are preserved.</p></div></div><form class="admin-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="seats"><input type="hidden" name="return_to" value="/admin/seats"><label>Flight<select name="flight_id" required><?php foreach($options['flights'] as $o): ?><option value="<?= (int)$o['id'] ?>"><?= $e($o['flight_number']) ?></option><?php endforeach ?></select></label><label>Rows<input name="rows" type="number" min="1" max="100" value="20" required></label><fieldset class="seat-letters"><legend>Seat letters</legend><?php foreach(range('A','K') as $letter): ?><label><input type="checkbox" name="letters[]" value="<?= $letter ?>" <?= strpos('ABCDEF',$letter)!==false?'checked':'' ?>><?= $letter ?></label><?php endforeach ?></fieldset><label>Cabin<select name="cabin_class"><?php foreach(['economy','premium_economy','business','first'] as $s): ?><option><?= $s ?></option><?php endforeach ?></select></label><button class="admin-button">Generate seats</button></form></section>
<section class="admin-card"><div class="card-heading"><div><h2>Seat availability</h2><p>Bulk changes apply to unreserved seats only.</p></div></div><div class="table-wrap"><table><thead><tr><th>Flight</th><th>Route / departure</th><th>Capacity</th><th>Availability</th><th>Bulk update</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= $e($r['flight_number']) ?></strong></td><td><?= $e($r['departure'].' → '.$r['arrival']) ?><small><?= $e($r['departure_at']) ?></small></td><td><?= (int)$r['capacity'] ?></td><td><?= (int)$r['available'] ?> available · <?= (int)$r['blocked'] ?> blocked</td><td><form class="inline-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="seat_status"><input type="hidden" name="flight_id" value="<?= (int)$r['flight_id'] ?>"><input type="hidden" name="return_to" value="/admin/seats"><select name="status"><option>available</option><option>blocked</option><option>unavailable</option></select><button class="small-button">Apply</button></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No flights available.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='bookings'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Bookings & passengers</h2><p>Reservation details and status.</p></div></div><div class="table-wrap"><table><thead><tr><th>PNR / customer</th><th>Flight</th><th>Passengers</th><th>Amount</th><th>Status / update</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= $e($r['pnr']) ?></strong><small><?= $e($r['full_name'].' · '.$r['email']) ?></small></td><td><?= $e($r['flight_number'].' · '.$r['departure'].' → '.$r['arrival']) ?></td><td><?= $e($r['passengers']??'—') ?></td><td><?= $e($r['currency'].' '.$r['total_amount']) ?></td><td><form class="inline-form" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="booking_status"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/bookings"><select name="status"><?php foreach(['pending','confirmed','cancelled','completed','expired'] as $s): ?><option <?= $r['status']===$s?'selected':'' ?>><?= $s ?></option><?php endforeach ?></select><button class="small-button">Save</button></form></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No bookings yet.</td></tr><?php endif ?></tbody></table></div></section>
<?php elseif($section==='payments'): ?>
<section class="admin-card"><div class="card-heading"><div><h2>Payment review</h2><p>Inspect proof and verify or reject submitted payments.</p></div></div><div class="table-wrap"><table><thead><tr><th>Booking / customer</th><th>Amount / method</th><th>Reference / proof</th><th>Status</th><th>Review</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= $e($r['pnr']) ?></strong><small><?= $e($r['full_name'].' · '.$r['email']) ?></small></td><td><?= $e($r['currency'].' '.$r['amount']) ?><small><?= $e(str_replace('_',' ',$r['method'])) ?></small></td><td><?= $e($r['transaction_reference']??'—') ?><?php if($r['proof_path']): ?><a class="proof-link" href="/admin/payment-proof?id=<?= (int)$r['id'] ?>">Download proof</a><?php endif ?></td><td><span class="badge <?= $e($r['status']) ?>"><?= $e($r['status']) ?></span></td><td><?php if(in_array($r['status'],['pending','submitted'],true)): ?><form class="review-actions" method="post" action="<?= $post ?>"><input type="hidden" name="_csrf" value="<?= $e($csrf) ?>"><input type="hidden" name="kind" value="payment"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="return_to" value="/admin/payments"><button class="small-button verify" name="decision" value="verified">Verify</button><button class="small-button reject" name="decision" value="rejected">Reject</button></form><?php else: ?><small>Booking <?= $e($r['booking_status']) ?></small><?php endif ?></td></tr><?php endforeach ?><?php if(!$rows): ?><tr><td colspan="5" class="empty">No payments submitted.</td></tr><?php endif ?></tbody></table></div></section>
<?php endif ?></main></div>
<nav class="admin-bottom-actions" aria-label="Quick actions"><a href="/admin/flights">＋<span>Flight</span></a><a href="/admin/bookings">▤<span>Bookings</span></a><a href="/admin/payments">✓<span>Payments</span></a></nav>
<script>
document.querySelectorAll('.admin-main table').forEach(table=>{const labels=[...table.querySelectorAll('thead th')].map(th=>th.textContent.trim());table.querySelectorAll('tbody tr').forEach(row=>row.querySelectorAll('td').forEach((cell,index)=>{if(!cell.hasAttribute('colspan')&&labels[index])cell.dataset.label=labels[index]}))});
const menuToggle=document.querySelector('.admin-menu-toggle');
document.querySelector('.admin-top')?.prepend(menuToggle);
menuToggle?.removeAttribute('onclick');
const sidebar=document.getElementById('admin-sidebar');
const backdrop=document.createElement('button');backdrop.type='button';backdrop.className='admin-backdrop';backdrop.setAttribute('aria-label','Close admin navigation');backdrop.tabIndex=-1;sidebar.before(backdrop);
const closeButton=document.createElement('button');closeButton.type='button';closeButton.className='admin-sidebar-close';closeButton.textContent='Close';closeButton.setAttribute('aria-label','Close admin navigation');sidebar.querySelector('.admin-brand').after(closeButton);
const setAdminNavOpen=open=>{document.body.classList.toggle('admin-nav-open',open);menuToggle?.setAttribute('aria-expanded',String(open));menuToggle?.setAttribute('aria-label',open?'Close admin navigation':'Open admin navigation');document.body.style.overflow=open?'hidden':'';if(open)closeButton.focus()};
menuToggle?.addEventListener('click',()=>setAdminNavOpen(!document.body.classList.contains('admin-nav-open')));
closeButton.addEventListener('click',()=>setAdminNavOpen(false));backdrop.addEventListener('click',()=>setAdminNavOpen(false));
sidebar.querySelectorAll('nav a').forEach(link=>link.addEventListener('click',()=>setAdminNavOpen(false)));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('admin-nav-open')){setAdminNavOpen(false);menuToggle?.focus()}});
window.addEventListener('resize',()=>{if(window.innerWidth>820&&document.body.classList.contains('admin-nav-open'))setAdminNavOpen(false)});
</script>
<?php require BASE_PATH.'/app/Views/layouts/footer.php'; ?>
